<?php

namespace App\Components;


class ErrorMessage
{
    const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
    const INTERNAL_ERROR = 'INTERNAL_ERROR';
    const RECORD_NOT_EXISTING = 'RECORD_NOT_EXISTING';
    const RECORD_EXISTING = 'RECORD_EXISTING';
    const RECORD_NOT_CREATED = 'RECORD_NOT_CREATED';
    const RECORD_NOT_UPDATED = 'RECORD_NOT_UPDATED';
    const RECORD_NOT_DELETED = 'RECORD_NOT_DELETED';
    const INVALID_INPUT = 'INVALID_INPUT';
    const INVALID_CRED = 'INVALID_CRED';
    const ACCESS_DENIED = 'ACCESS_DENIED';
    const ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND';
    const CANNOT_PERFORM_ACTION = 'CANNOT_PERFORM_ACTION';
    const DUPLICATE_ENTRY = 'DUPLICATE_ENTRY';
    const OUT_OF_STOCK = 'OUT_OF_STOCK';
}
